version: '3'
services:
  nginx:
    image: nginx:1.15.7-alpine
    ports:
      - 4200:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    links:
      - php
  php:
    build: .
    volumes:
      - ./php:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./log:/var/log