version: '3'
services:
  nginx:
    image: nginx:1.15.7-alpine
    ports:
      - "3900:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
      - ./html:/var/www/html:cached
    depends_on:
      - php
  php:
    build: ./php
    ports:
      - "9000"
    volumes:
      - ./html:/var/www/html:cached
      - ./php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./log:/var/log:cached
